### ISSUE TITLE
Errore durante il salvataggio del modello della cGAN

### ISSUE THREAD

**Issue by dpassaro** [Dario-Caf/EM-shower-simulator-with-NN#1]
Caro Dott. Cafasso, durante la compilazione in locale di "cGAN_versione1.py" viene generato il seguente errore. Esce anche a lei o è un problema della mia machina ?

```
Traceback (most recent call last):
  File "cGAN_versione1.py", line 411, in <module>
    cond_gan.save("model.h5")
  File "/home/daniele/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1211, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/home/daniele/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 106, in save_model
    'Saving the model to HDF5 format requires the model to be a '
NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. 
It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. 
Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using "save_weights". 
```

**Comment by Dario-Maglio** [comment]
Gentile Dott. Passaro, era un problema condiviso e appena risolto alla radice cambiando metodo di salvataggio.
